---
# tasks file for lamp
# Installation Apache
- name: Installation Apache
  apt:
    name:
      - apache2
      - libapache2-mod-php

- name: Installation PHP
  apt:
    name:
      - php-common
      - php-mysql

- name: Installation MySQL
  apt:
    name:
      - mysql-server

- name: Modification du fichier vhost par défaut Apache 
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    notify: restart apache

- name: Donner la propriété du répertoire racine à l'utilisateur www-data
  file:
    path: "/var/www/html"
    state: directory
    owner: "www-data"
    group: "www-data"
    mode: 0755



